# Generated by Django 4.1.5 on 2023-01-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmitter', '0002_notification_be_read_notification_pre_be_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmroom',
            name='be_read',
            field=models.BooleanField(default=False),
        ),
    ]
