# Generated by Django 4.1.5 on 2023-01-15 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmitter', '0003_dmroom_be_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmroom',
            name='be_read',
        ),
        migrations.AddField(
            model_name='dmroom',
            name='has_read_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
