from django.urls import path, include
from tmitter import views

urlpatterns = [
    path('', views.top, name="top"),
    # path('test/', views.test, name="test"),
    path('delete/', views.delete_tmeet, name="delete_tmeet"),
    path('home/', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('create_tmeet/', views.create_tmeet, name="create_tmeet"),
    path('tmeet_detail/<int:tmeet_id>/', views.tmeet_detail, name="tmeet_detail"),
    path('following_list/<str:user_name>/', views.following_list, name="following_list"),
    path('follower_list/<str:user_name>/', views.follower_list, name="follower_list"),
    path('tmeet_detail_content', views.tmeet_detail_content, name="tmeet_detail_content"),
    path('home_tmeet_content', views.home_tmeet_content, name="home_tmeet_content"),
    path('following_list_content', views.following_list_content, name="following_list_content"),
    path('follower_list_content', views.follower_list_content, name="follower_list_content"),
    path('explored_user_content', views.explored_user_content, name="explored_user_content"),
    path('explored_tmeet_content', views.explored_tmeet_content, name="explored_tmeet_content"),
    path('user_page_content', views.user_page_content, name="user_page_content"),
    path('like/', views.like, name="like"),
    path('follow/', views.follow, name='follow'),
    path('explore/', views.explore, name='explore'),
    path('setting/', views.setting, name='setting'),
    path('notification/', views.notification, name='notification'),
    path('messages/create_dm_room/<int:user_id>/', views.create_dm_room, name='create_dm_room'),
    path('messages/search_user/', views.search_talk_with_user, name='search_talk_with_user'),
    path('messages/<str:user_name>/<int:dm_room_id>/', views.dm_room, name='dm_room'),
    path('messages/', views.messages, name='messages'),
    path('send_message', views.send_message, name='send_message'),
    path('dm_room_content/<str:user_name>/<int:dm_room_id>/', views.dm_room_content, name='dm_room_content'),
    path('search_talk_with_user_content', views.search_talk_with_user_content, name='search_talk_with_user_content'),
    path('check_new_noti_and_dm', views.check_new_noti_and_dm, name='check_new_noti_and_dm'),
    path('<str:user_name>/', views.user_page, name="user_page"),
]
